### ISSUE TITLE
Unusual behavior when passing Rails.root.join to RGeo::Shapefile::Reader.open

### ISSUE THREAD

**Issue by msimonborg** [rgeo/rgeo-shapefile#21]
Hi, 

First off I want to say how much I appreciate your libraries and blog posts, which make diving into spatial programming so much less intimidating.

I needed to upload shapefiles in a rails app, and did something like this
```RGeo::Shapefile::Reader.open(Rails.root.join('shape', 'file', 'name.shp')) do |file|```
which would give me a file not found error referencing a path like this
```/lib/shape/file/name/.shp```  <--- extra slash before `.shp`

The extra slash was not there when I ran `Rails.root.join('shape', 'file', 'name.shp')` on its own, and `Rails.root.join('shape', 'file', 'name.shp').to_s` printed the string just fine.

So I passed `Rails.root.join('shape', 'file', 'name.shp').to_s` as an argument to `RGeo::Shapefile::Reader.open` and that worked.

This is clearly not a big issue, but is inconsistent with the behavior of other file readers like `File.open` and `File.read`, so it caused some confusion. It should either be in the documentation, or patched.

I submitted a pull request with a patch to fix the issue.

**Comment by nijikon** [comment]
#20
