### ISSUE TITLE
GEOS is not available, but is required for correct interpretation of polygons in shapefiles in rails console on OS X

### ISSUE THREAD

**Issue by wuliwong** [rgeo/rgeo-shapefile#25]
When I attempt:

I am running:

os-x "High Sierra"  10.13.2
ruby 2.4.0p0
ruby on rails (5.1.1)
rgeo-shapefile (0.2.3)
dbf (3.1.1)
rgeo (1.0.0)
geos (3.6.2) which installed via `brew install geos`

In a `rails console` when I run the example

```
require 'rgeo/shapefile'

RGeo::Shapefile::Reader.open('my_shapefile.shp') do |file|
  puts "File contains #{file.num_records} records."
  file.each do |record|
    puts "Record number #{record.index}:"
    puts "  Geometry: #{record.geometry.as_text}"
    puts "  Attributes: #{record.attributes.inspect}"
  end
  file.rewind
  record = file.next
  puts "First record geometry was: #{record.geometry.as_text}"
end
```

I receive the output

```
File contains 83 records.
RGeo::Error::RGeoError: GEOS is not available, but is required for correct interpretation of polygons in shapefiles.
```
'my_shapefile.shp' was a Zillow neighborhood file for Georgia.

Additional note is if I open `irb` in a directory _other than_ this rails app and run:

```
require 'rgeo'
RGeo::Geos.supported?
```
it returns  `true`

Running the same commands in `irb` _inside_ the rails app root directory returns `false`.

**Comment by wuliwong** [comment]
I was able to solve the problem by uninstalling `rgeo` then running

`ARCHFLAGS="-arch x86_64" gem install rgeo`

**Comment by teeparham** [comment]
Seems like this is fixed.
