### ISSUE TITLE
Get "unknown encoding name" when reading shapefile (with encoding "1252")

### ISSUE THREAD

**Issue by moonhouse** [rgeo/rgeo-shapefile#39]
I have a dataset where the .cpg file contains `1252`. When I'm trying to read it using the code example code in the [README file](https://github.com/rgeo/rgeo-shapefile/blob/master/README.md) file I get an error:

```
File contains 1407 records.
Traceback (most recent call last):
	12: from read_shape.rb:3:in `<main>'
	11: from /Users/davidhall/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rgeo-shapefile-3.0.0/lib/rgeo/shapefile/reader.rb:164:in `open'
	10: from read_shape.rb:5:in `block in <main>'
	 9: from /Users/davidhall/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rgeo-shapefile-3.0.0/lib/rgeo/shapefile/reader.rb:346:in `each'
	 8: from /Users/davidhall/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rgeo-shapefile-3.0.0/lib/rgeo/shapefile/reader.rb:402:in `_read_next_record'
	 7: from /Users/davidhall/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/dbf-4.1.3/lib/dbf/record.rb:41:in `attributes'
	 6: from /Users/davidhall/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/dbf-4.1.3/lib/dbf/record.rb:62:in `attribute_map'
	 5: from /Users/davidhall/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/dbf-4.1.3/lib/dbf/record.rb:62:in `map'
	 4: from /Users/davidhall/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/dbf-4.1.3/lib/dbf/record.rb:62:in `block in attribute_map'
	 3: from /Users/davidhall/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/dbf-4.1.3/lib/dbf/record.rb:81:in `init_attribute'
	 2: from /Users/davidhall/.rbenv/versions/2.7.2/lib/ruby/2.7.0/forwardable.rb:235:in `type_cast'
	 1: from /Users/davidhall/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/dbf-4.1.3/lib/dbf/column_type.rb:93:in `type_cast'
/Users/davidhall/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/dbf-4.1.3/lib/dbf/column_type.rb:93:in `force_encoding': unknown encoding name - 1252 (ArgumentError)
```

which means it fails on the line with `file.each do |record|`.

If I remove the .cpg file I get the expected output (although the character encoding of entries in the .dbf file is in their original encoding).

```
File contains 1407 records.
Record number 0:
  Geometry: MULTILINESTRING ((670991.8130000002 6586111.595, 670988.0530000001 6586118.062))
  Attributes: {"NAMN"=>"Vallgatan", "RLID"=>"1000:81910", "STARTAVST"=>0.0, "SLUTAVST"=>1.0, "SHAPE_LEN"=>7.48062089691, "FRAN_DATUM"=>20150401, "TILL_DATUM"=>99991231, "RIKTNING"=>"Med", "ORDNING"=>5, "ROLL"=>"Syskon fram", "VARD"=>-1}
Record number 1:
  Geometry: MULTILINESTRING ((671080.767 6586054.39, 671065.354 6586046.85, 671043.831 6586035.552, 671036.76 6586031.134))
  Attributes: {"NAMN"=>"Enk\xF6pingsv\xE4gen", "RLID"=>"1000:81930", "STARTAVST"=>0.0, "SLUTAVST"=>1.0, "SHAPE_LEN"=>49.8042869817, "FRAN_DATUM"=>20150401, "TILL_DATUM"=>99991231, "RIKTNING"=>"Med", "ORDNING"=>2, "ROLL"=>"Syskon bak", "VARD"=>-1}
[…]
```

I have tried to change the contents in the .cpg file to other values like "cp1252", "CP1252", "Windows-1252", "windows-1252" but I get an "unknown encoding name" error for everyone of those.

If I use open the .dbf file using the dbf gem I get using the following code

```
require 'dbf'

data = DBF::Table.new('solna/Solna_kommun_ShapeNVDB_DKGatunamn.dbf', nil, '1252')
data.each do |d|
    p d.attributes
end
```
I get the same "unknown encoding name" error but I can read the attributes when the values "cp1252" or "windows-1252" is used in the third parameter in the DBF::Table.new call.

```
{"NAMN"=>"Vallgatan", "RLID"=>"1000:81910", "STARTAVST"=>0.0, "SLUTAVST"=>1.0, "SHAPE_LEN"=>7.48062089691, "FRAN_DATUM"=>20150401, "TILL_DATUM"=>99991231, "RIKTNING"=>"Med", "ORDNING"=>5, "ROLL"=>"Syskon fram", "VARD"=>-1}
{"NAMN"=>"Enköpingsvägen", "RLID"=>"1000:81930", "STARTAVST"=>0.0, "SLUTAVST"=>1.0, "SHAPE_LEN"=>49.8042869817, "FRAN_DATUM"=>20150401, "TILL_DATUM"=>99991231, "RIKTNING"=>"Med", "ORDNING"=>2, "ROLL"=>"Syskon bak", "VARD"=>-1}
```

**Version info**
```
$ ruby -v
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin18]
```

```
$ bundle list
Gems included by the bundle:
  * dbf (4.1.3)
  * rgeo (2.1.1)
  * rgeo-shapefile (3.0.0)
```

**Comment by keithdoggett** [comment]
Sorry, must've missed this when you submitted it. Is this still an issue or were you able to fix it?

**Comment by rywall** [comment]
@moonhouse https://github.com/rgeo/rgeo-shapefile/pull/43 should solve this.

**Comment by moonhouse** [comment]
> @moonhouse #43 should solve this.

Thanks! Using #43 I can parse the file without any error. (With an extra `.force_encoding("cp1252").encode("utf-8")` on the text attributes I can get them in the encoding I expect.)

**Comment by rywall** [comment]
@moonhouse I re-read your original comment a bit more closely. I would have expected that if you changed the contents of the `.cpg` file to `cp1252` then it would have worked. Is there a newline at the end of your `.cpg` file? Maybe we should call `.strip` on the encoding name before validating it.

**Comment by moonhouse** [comment]
> I would have expected that if you changed the contents of the `.cpg` file to `cp1252` then it would have worked. Is there a newline at the end of your `.cpg` file?

Ah, yes! I didn't think about the newline that my text editor added.

If I do `echo -n "cp1252" > solna/Solna_kommun_ShapeNVDB_DKGatunamn.cpg` and then run the code above with the release version 3.0.0 of the gem it works fine (and it decodes it nicely as well).

**Comment by moonhouse** [comment]
(However, I do appreciate the version in #43 where I can parse the files in read-only mode without having to overwrite the files first.)
