### ISSUE TITLE
No such file or directory, Rails 4 and Ruby 2

### ISSUE THREAD

**Issue by bgribbin** [rgeo/rgeo-shapefile#6]
Hi Daniel,

I'm working through your 2nd project in the RailsConf 2012 and found a problem trying to open an shp file.

In the console
File.exists?(Rails.root.join('lib/tasks.uk.shp))
=> true

In my data.rb file:

factory = Region::GEOFACTORY
    RGeo::Shapefile::Reader.open(Rails.root.join('lib/tasks/uk.shp'), :factory => factory) do |file|
        file.each do |record|
            tzid = record['TZID']
            region = Region.where(:name => tzid).first ||
             Region.create(:name => tzid)
            record.geometry.projection.each do |polygon|
                region.regions.create(:poly => polygon)
            end
        end
    end

Output:

/usr/local/rvm/gems/ruby-2.0.0-p247/gems/rgeo-shapefile-0.2.3/lib/rgeo/shapefile/reader.rb:226:in `initialize': No such file or directory - /Users/bgribbin/Projects/location2/lib/tasks/uk/.shp (Errno::ENOENT)

It looks like its splitting the filename in half?

Any help would be appreciated

Thanks

**Comment by msimonborg** [comment]
This issue was forever ago, but I just had the same problem. appending `.to_s` onto `Rails.root.join(file_name)` worked for me
