### ISSUE TITLE
record.geometry is nil on Linux but a geometry on Windows

### ISSUE THREAD

**Issue by kamilpogo** [rgeo/rgeo-shapefile#8]
Hello Daniel,
thanks for the great library!

I found strange behaviour with RGeo::Shapefile. 

My setup:
Windows
ruby 2.0.0p247 (2013-06-27) [i386-mingw32]
Linux
ruby 2.0.0p195 (2013-05-14 revision 40734) [i686-linux]

```
RGeo::VERSION = 0.3.20
RGeo::Shapefile::VERSION = 0.2.3
```

Data: http://biogeo.ucdavis.edu/data/gadm2/gadm_v2_shp.zip (big file!)

``` ruby
require 'rgeo/shapefile'

RGeo::Shapefile::Reader.open('gadm2.shp', :assume_inner_follows_outer => true) do |file|
  puts "File contains #{file.num_records} records."
  record = file[28758]
  if record.geometry.nil?
    puts "  Geometry: nil" 
  else    
    puts "  Geometry: #{record.geometry.as_text}" 
  end
end
```

When reading record number 28758 (it's this specific record causing problems) I get following results:

Linux:

```
ruby shape_reader.rb
File contains 218238 records.
  Geometry: nil
```

Windows:

```
ruby shape_reader.rb
File contains 218238 records.
  Geometry: MULTIPOLYGON (((-105.38739776611328 52.405689239501896, -105.38725280761719 52.405693054199276, -105.3871078491211 52.405693054199276, -105.38695526123047 52.4056930541
99276, -105.38681030273432 52.405693054199276, -105.38666534423828 52.405693054199276, -105.3865127563476 52.405693054199276, -105.38636779785156 52.405693054199276, -105.386222839
35541 52.405696868896484, -105.38607025146484 52.405696868896484, -105.3859252929687 52.405696868896484, -105.38578033447266 52.405696868896484, -105.3856353759765 52.4056968688964
84, -105.38549041748047 52.405696868896484, -105.38534545898438 52.405696868896484, -105.38519287109364 52.405696868896484, -105.38504791259766 52.405696868896484, -105.38490295410
.......
```

Do you have an idea why the code can't read the geometry on Linux? Shouldn't there be an exception when it fails reading data telling why it failed?

**Comment by leoromanovsky** [comment]
Did you get it resolved?

**Comment by rossettistone** [comment]
I'm way out on a limb here, but this could be related to a reported issue on `rgeo`: https://github.com/rgeo/rgeo/issues/113
I'm rather new to GIS in general, and `rgeo` specifically - linking it here in the hopes that someone more veteran might have a clue what's going on.

**Comment by teeparham** [comment]
Closing as stale. Please re-open with a small sample data set if this is still a problem.
